apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: argocd-tenant-config
spec:
  rules:
  - name: argocd-tenant-cluster
    context:
     apiCall:
       urlPath: "/api/v1/namespaces/{{request.object.spec.chart.spec.sourceRef.namespace}}"
       jmesPath: "metadata.labels.\"tenant.nsm.bedag.ch/name\"" 
    match:
      any:
      - resources:
          kinds:
          - Tenant
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - default
          - kube-public
          - kyverno
    generate:
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: {{request.object.metadata.name}}-argocd-tenant
      # generate the resource in the new namespace
      namespace: "argocd"
      data:
        kind: Secret
        metadata:
          labels:
             argocd.argoproj.io/secret-type: cluster
        type: Opaque
        stringData:
          name: {{request.object.metadata.name}}
          server: https://mycluster.com
          config: |
            {
              "bearerToken": "<authentication token>",
              "tlsClientConfig": {
                "insecure": true,
              }
            }